before_install:
  - docker build -t matthewutzig/civcraft-wiki -f Dockerfile .

script:
  - docker run matthewutzig/civcraft-wiki go test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "civilizationcraft-wiki"
  env: "civcraft-env"
  bucket_name: "elasticbeanstalk-us-east-1-237329159398"
  bucket_path: "civilizationcraft-wiki"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
